### ISSUE TITLE
engine inanis

### ISSUE THREAD

**Issue by laripette** [Tearth/Inanis#2]
I would like to know if your cosette engine is abandoned ?
is it your new inanis engine that replaces it ?
will there be soon executable files for inanis ?

**Comment by Tearth** [comment]
Hi, indeed Cosette is no longer developed because at some point I've realized that using .NET/C# wasn't the perfect choice, also I learned how to test changes better and more accurately - so the decision was to end the project which was already on a very stable level and move onto the new engine. Inanis doesn't have any official releases yet because it's still not as ready as I want, but maybe within weeks I will decide to make one - of course you can always build executables yourself if you know Rust toolchain, the engine should be rather stable at this point.

**Comment by laripette** [comment]
thank you for your answer.
